apiVersion: v1
kind: Pod                     # 使用pod能固定容器的名称，但是不能设置副本数，所以要注意。
metadata:
  namespace: cloudai-2     # 设置命名空间
  name: hbase-master-1
  labels:
    app: hbase-master-pod-1
spec:
  imagePullSecrets:
  - name: hubsecret              # 镜像拉取秘钥
  containers:
    - name: hbase-master-1
      image: mldp/cloud:hadoop-hbase-1.0.7
#      command: ['/opt/hbase/bin/start-k8s-hbase.sh']
      ports:
        - containerPort: 60000
        - containerPort: 60001
        - containerPort: 9090
      env:
        - name: HBASE_SERVER_TYPE     # hbase角色类型。根据 HBASE_SERVER_TYPE 的取值来确定是启master还是regionserver
          value: master
        - name: MASTER_DEBUG    # 是否启动调试模式，启动后，不会自动启动master
          value: "no"
        - name: START_THRIFT     # 是否启动thrift
          value: "yes"
        - name: HBASE_MASTER_PORT    # hbase的master端口号
          value: "60000"
        - name: HBASE_MASTER_INFO_PORT  # hbase的master信息端口号
          value: "60001"
        - name: HBASE_REGION_PORT    # hbase的region端口号
          value: "60010"
        - name: HBASE_REGION_INFO_PORT   # hbase的region的信息端口号
          value: "60011"
        - name: HDFS_SERVICE   # hdfs服务，HDFS_SERVICE为HDFS服务经过skyDNS之后的对应域名，若未设置skyDNS则此处值设为HDFS服务对应的IP地址
          value: "10.233.9.2"   # hdfs的集群ip
        - name: HDFS_PORT   # hdfs端口号
          value: "4231"
        - name: ZOOKEEPER_SERVICE_LIST   # zookeeper列表，域名，同HDFS_SERVICE意义
          value: "10.233.9.11,10.233.9.12,10.233.9.13"   # zookeeper集群ip
        - name: ZOOKEEPER_PORT   # zookeeper端口号
          value: "2181"
        - name: ZNODE_PARENT   # znode_parent
          value: hbase
        - name: HBASE_MASTER_LIST   # 为HBase集群中除当前master外的其余master的服务地址和pod名的对应关系。格式为 <master服务IP地址>:<master对应Pod名>，多个项之间以空格分隔
          value: "10.233.9.22:hbase-master-2"
        - name: HBASE_REGION_LIST  # 为HBase集群中除当前regionserver外的其余regionserver的服务地址和pod名的对应关系
          value: "10.233.9.23:hbase-region-1 10.233.9.24:hbase-region-2"
  restartPolicy: Always     #　表示如果该Pod挂掉的话将一直尝试重新启动它

