apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbase-region-deployment-1     # 部署的名称，部署负责pod的正常运行个数，不负责pod内分布式处理
  namespace: cloudai-2
spec:   # 包括一些container，storage，volume以及其他Kubernetes需要的参数，以及诸如是否在容器失败时重新启动容器的属性。可在特定Kubernetes API找到完整的Kubernetes Pod的属性。
  selector:    
    matchLabels:
      app: hbase-region-pod-1   # 根据标签选择选择部署下一层的容器组，复制保持容器组的正常运行个数
  replicas: 1   # 选项定义需要的副本个数，此处可以设置很多属性，例如受此Deployment影响的Pod的选择器等
  template:   # template其实就是对Pod对象的定义。没有为pod指定名称，会自动在deployment的名称后面加随机字符串
    metadata:
      labels:
        app: hbase-region-pod-1   # 为容器组（pod）打标签，
    spec: 
      restartPolicy: Always     #　表示如果该Pod挂掉的话将一直尝试重新启动它
      imagePullSecrets:
      - name: hubsecret
      containers:
      - name: hbase-region-container-1     # 容器名称
        image: mldp/cloud:hadoop-hbase-1.0.7    # 基于的镜像名, 根据镜像创建容器
#        command: ['sleep','30000']
        ports:
          - containerPort: 60000
          - containerPort: 60001
        env:
          - name: HBASE_SERVER_TYPE     # hbase角色类型。根据 HBASE_SERVER_TYPE 的取值来确定是启master还是regionserver
            value: regionserver
          - name: MASTER_DEBUG    # 是否启动调试模式，启动后，不会自动启动master
            value: "yes"
          - name: START_THRIFT     # 是否启动thrift
            value: "no"
          - name: HBASE_MASTER_PORT    # hbase的master端口号
            value: "60000"
          - name: HBASE_MASTER_INFO_PORT  # hbase的master信息端口号
            value: "60001"
          - name: HBASE_REGION_PORT    # hbase的region端口号
            value: "60010"
          - name: HBASE_REGION_INFO_PORT   # hbase的region的信息端口号
            value: "60011"
          - name: HDFS_SERVICE   # hdfs服务，HDFS_SERVICE为HDFS服务经过skyDNS之后的对应域名，若未设置skyDNS则此处值设为HDFS服务对应的IP地址
            value: "10.233.9.2"   # hdfs的集群ip
          - name: HDFS_PORT   # hdfs端口号
            value: "4231"
          - name: ZOOKEEPER_SERVICE_LIST   # zookeeper列表，域名，同HDFS_SERVICE意义
            value: "10.233.9.11,10.233.9.12,10.233.9.13"  # zookeeper集群ip，这里使用hbase自带的zookeeper
          - name: ZOOKEEPER_PORT   # zookeeper端口号
            value: "2181"
          - name: ZNODE_PARENT   # znode_parent
            value: hbase
          - name: HBASE_MASTER_LIST   # 为HBase集群中除当前master外的其余master的服务地址和pod名的对应关系。格式为 <master服务IP地址>:<master对应Pod名>，多个项之间以空格分隔
            value: "10.233.9.21:hbase-master-1 10.233.9.22:hbase-master-2"
          - name: HBASE_REGION_LIST  # 为HBase集群中除当前regionserver外的其余regionserver的服务地址和pod名的对应关系
            value: "10.233.9.23:hbase-region-1 10.233.9.24:hbase-region-2"
# 第一遍启动使用睡眠命令，进入pod后，复制配置文件过去，删除服务重新创建      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbase-region-deployment-2     # 部署的名称，部署负责pod的正常运行个数，不负责pod内分布式处理
  namespace: cloudai-2
spec:   # 包括一些container，storage，volume以及其他Kubernetes需要的参数，以及诸如是否在容器失败时重新启动容器的属性。可在特定Kubernetes API找到完整的Kubernetes Pod的属性。
  selector:    
    matchLabels:
      app: hbase-region-pod-2   # 根据标签选择选择部署下一层的容器组，复制保持容器组的正常运行个数
  replicas: 1   # 选项定义需要的副本个数，此处可以设置很多属性，例如受此Deployment影响的Pod的选择器等
  template:   # template其实就是对Pod对象的定义。没有为pod指定名称，会自动在deployment的名称后面加随机字符串
    metadata:
      labels:
        app: hbase-region-pod-2   # 为容器组（pod）打标签，
    spec: 
      restartPolicy: Always     #　表示如果该Pod挂掉的话将一直尝试重新启动它
      imagePullSecrets:
      - name: hubsecret
      containers:
      - name: hbase-region-container-1     # 容器名称
        image: mldp/cloud:hadoop-hbase-1.0.7    # 基于的镜像名, 根据镜像创建容器
#        command: ['sleep','30000']
        ports:
          - containerPort: 60000
          - containerPort: 60001
        env:
          - name: HBASE_SERVER_TYPE     # hbase角色类型。根据 HBASE_SERVER_TYPE 的取值来确定是启master还是regionserver
            value: regionserver
          - name: MASTER_DEBUG    # 是否启动调试模式，启动后，不会自动启动master
            value: "yes"
          - name: START_THRIFT     # 是否启动thrift
            value: "no"
          - name: HBASE_MASTER_PORT    # hbase的master端口号
            value: "60000"
          - name: HBASE_MASTER_INFO_PORT  # hbase的master信息端口号
            value: "60001"
          - name: HBASE_REGION_PORT    # hbase的region端口号
            value: "60010"
          - name: HBASE_REGION_INFO_PORT   # hbase的region的信息端口号
            value: "60011"
          - name: HDFS_SERVICE   # hdfs服务，HDFS_SERVICE为HDFS服务经过skyDNS之后的对应域名，若未设置skyDNS则此处值设为HDFS服务对应的IP地址
            value: "10.233.9.2"   # hdfs的集群ip
          - name: HDFS_PORT   # hdfs端口号
            value: "4231"
          - name: ZOOKEEPER_SERVICE_LIST   # zookeeper列表，域名，同HDFS_SERVICE意义
            value: "10.233.9.11,10.233.9.12,10.233.9.13"   # zookeeper集群ip，这里使用hbase自带的zookeeper
          - name: ZOOKEEPER_PORT   # zookeeper端口号
            value: "2181"
          - name: ZNODE_PARENT   # znode_parent
            value: hbase
          - name: HBASE_MASTER_LIST   # 为HBase集群中除当前master外的其余master的服务地址和pod名的对应关系。格式为 <master服务IP地址>:<master对应Pod名>，多个项之间以空格分隔
            value: "10.233.9.21:hbase-master-1 10.233.9.22:hbase-master-2"
          - name: HBASE_REGION_LIST  # 为HBase集群中除当前regionserver外的其余regionserver的服务地址和pod名的对应关系
            value: "10.233.9.23:hbase-region-1 10.233.9.24:hbase-region-2"
# 第一遍启动使用睡眠命令，进入pod后，复制配置文件过去，删除服务重新创建      
